---

- name: set journald config
  template:
    src: 'journald.conf.j2'
    dest: '/etc/systemd/journald.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: restart journald

- name: ensure journald is enabled/started
  systemd:
    name: 'systemd-journald'
    enabled: yes
    state: started

...
