---

- name: install cronie/crond
  package:
    state: present
    name:
      - "cronie"
      - "cronie-anacron"
      - "crontabs"

- name: remove noanacron
  package:
    state: absent
    name: "cronie-noanacron"

- name: fix folder permissions
  file:
    path: "{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'
  with_items:
    - "/etc/cron.d"
    - "/etc/cron.hourly"
    - "/etc/cron.daily"
    - "/etc/cron.weekly"
    - "/etc/cron.monthly"

- name: ensure permissions on root crontab/anacrontab
  file:
    path: "{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  with_items:
    - "/etc/crontab"
    - "/etc/anacrontab"

- name: setup user allow list
  include_tasks: allow.yml
  when: crond_access_mode == "allow"

- name: setup user deny list
  include_tasks: deny.yml
  when: crond_access_mode == "deny"

- name: start/enable crond
  systemd:
    name: 'crond'
    enabled: yes
    state: started

...
