---

- name: Install SELinux python2 tools
  package:
    name:
      - "libselinux-python"
      - "policycoreutils-python"
    state: present
  when: "ansible_python_version is version('3', '<')"

- name: Install SELinux python3 tools
  package:
    name:
      - "libselinux-python3"
      - "policycoreutils-python3"
    state: present
  when: "ansible_python_version is version('3', '>=')"

- name: Install SELinux tool semanage
  package:
    name:
      - "policycoreutils-python-utils"
    state: present
  when: ( ansible_distribution_major_version > "7" ) and ( ansible_distribution == "CentOS" or ansible_distribution == "RedHat" )

- name: set selinux state
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_mode }}"
  when: selinux_mode != "disabled"

- name: set selinux state
  selinux:
    state: "{{ selinux_mode }}"
  when: selinux_mode == "disabled"
